# Generated by Django 2.2.7 on 2019-11-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.URLField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
