# Generated by Django 2.2.7 on 2019-11-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image_credits',
            field=models.TextField(default='ME', max_length=250),
            preserve_default=False,
        ),
    ]
