# Generated by Django 2.2.7 on 2019-11-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forum_image_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='mini_desc',
            field=models.TextField(default='moini mini'),
            preserve_default=False,
        ),
    ]
